### ISSUE TITLE
root key management

### ISSUE THREAD

**Issue by Hefeweizen** [attachmentgenie/attachmentgenie-ssh#24]
Thanks for the module, it's been helpful.

Currently, the module allows root login, though it suggests it's bad practice.

For key management (i.e. ssh::user), it does not consider the case of root, assuming a path of '/home/<user>'.  I would expect this as oversight, but I'm asking just in case it's not.

Would you welcome a patch to support setting root ssh keys, or has that functionality been purposefully left out to discourage the practice?

Thanks.

**Comment by attachmentgenie** [comment]
good to hear its been useful, the omission is an oversight on my part, as i personally never allow root ssh access. the patch would be most welcome

**Comment by Hefeweizen** [comment]
I'll work on it.

**Comment by Hefeweizen** [comment]
Ok, this is what I came up with: https://github.com/attachmentgenie/attachmentgenie-ssh/commit/2743992aafcbcfae3af6ffbb83fc4257f71eb5cb.  But, it doesn't work.

On my test node, 'File[/root]' fails.  But in looking at troubleshooting this, I find myself asking what the purpose of the require chains are?  They seem redundant as ssh_authorized_keys autorequires the user itself.

**Comment by attachmentgenie** [comment]
looking into this again, i agree ssh_authorized_keys will correctly do this for you removing the require
