### ISSUE TITLE
Manage ssh private and public server host keys content

### ISSUE THREAD

**Issue by jordiclariana** [attachmentgenie/attachmentgenie-ssh#25]
Hi,

Have you considered to support private and public server host keys content?
I mean this files:

/etc/ssh/ssh_host_dsa_key
/etc/ssh/ssh_host_dsa_key.pub
/etc/ssh/ssh_host_ecdsa_key
/etc/ssh/ssh_host_ecdsa_key.pub
/etc/ssh/ssh_host_rsa_key
/etc/ssh/ssh_host_rsa_key.pub

Doing so you can ensure that a host, even after reinstallation, will have the same host key, so other hosts that usually connect to this via ssh will not throw the typical: "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED". This is important when you have some automatic procedures that relay on interchanged fingerprints.

Do you see any security issues here?

Regards.

**Comment by attachmentgenie** [comment]
although other modules like saz/ssh support this feature; i personally feel uncomfortable supporting this feature. 

 Because there are some security implications as you correctly mention, although there can be some benign reasons for this change,  there are also some that are definitely not.
