### ISSUE TITLE
Option PermitTTY in sshd_config not available in Ubuntu 12.04

### ISSUE THREAD

**Issue by rogermartensson** [attachmentgenie/attachmentgenie-ssh#48]
It looks like PermitTTY is not a valid keyword in sshd_config för Ubuntu 12.04 (precise).

**Comment by attachmentgenie** [comment]
grouping the PermitTTY fall out here.

Pull requests #44 and #49 try to address this problem. 

PermitTTY was introduced in version 6.5 of openssh [1]. Looking at distrowatch i concluded that a version equal to or higher than 6.5 was introduced in ubuntu in trusty [2], debian in jessie [3] and centos in 7 [4].

Altough the code in #44 now allows us to undef the permittty setting ill be adding some more code to set the correct defaults

[1] http://www.openssh.com/txt/release-6.5
[2] https://distrowatch.com/table.php?distribution=ubuntu
[3] https://distrowatch.com/table.php?distribution=debian
[4] https://distrowatch.com/table.php?distribution=centos

**Comment by attachmentgenie** [comment]
the module no correctly applies to the following test OS/Puppet matrix

´´´
!?master ~/Devshed/Projects/attachmentgenie-ssh> bundle exec kitchen list
Instance             Driver   Provisioner  Verifier  Transport  Last Action
puppet3-ubuntu-1204  Vagrant  PuppetApply  Inspec    Ssh        <Not Created>
puppet3-ubuntu-1404  Vagrant  PuppetApply  Inspec    Ssh        <Not Created>
puppet3-debian-711   Vagrant  PuppetApply  Inspec    Ssh        <Not Created>
puppet3-debian-85    Vagrant  PuppetApply  Inspec    Ssh        <Not Created>
puppet3-centos-68    Vagrant  PuppetApply  Inspec    Ssh        <Not Created>
puppet3-centos-72    Vagrant  PuppetApply  Inspec    Ssh        <Not Created>
puppet4-ubuntu-1404  Vagrant  PuppetApply  Inspec    Ssh        Converged
puppet4-ubuntu-1604  Vagrant  PuppetApply  Inspec    Ssh        Converged
puppet4-debian-711   Vagrant  PuppetApply  Inspec    Ssh        Converged
puppet4-debian-85    Vagrant  PuppetApply  Inspec    Ssh        Converged
puppet4-centos-68    Vagrant  PuppetApply  Inspec    Ssh        Converged
puppet4-centos-72    Vagrant  PuppetApply  Inspec    Ssh        Converged
´´´
