### ISSUE TITLE
Merge with dev-sec/puppet-ssh-hardening

### ISSUE THREAD

**Issue by chris-rock** [attachmentgenie/attachmentgenie-ssh#52]
Dear @attachmentgenie Awesome work on this puppet module. Would you be interested in bringing your expertise over to https://github.com/dev-sec/puppet-ssh-hardening?

**Comment by attachmentgenie** [comment]
Dear @chris-rock i am definitely be interested in helping you out getting the dev-sec/puppet-ssh-hardening up to date. How can i help?

**Comment by chris-rock** [comment]
Sure thing, I invite you to the dev-sec contributors! Thank you!

**Comment by attachmentgenie** [comment]
exiting days!
