### ISSUE TITLE
PermitRootLogin should support prohibit-password, without-password and forced-commands-only

### ISSUE THREAD

**Issue by akhowell** [attachmentgenie/attachmentgenie-ssh#54]
These 3 options are valid for PermitRootLogin as well as yes and no. We were previously running an older version of the module, however we've recently updated to puppet 4.x and version 2.1.0 of the module, and noticed that line 161 of server.pp now restricts valid answers to yes or no. This regular expression should be expanded to support the other 3 answers as valid also.

**Comment by attachmentgenie** [comment]
@akhowell thanks for your feedback, i have made the required changes and publish version 3.0.0 to the forge
